[tool.towncrier]
name = "Input4MIPs CVs"
version = "6.5.11a1"
filename = "docs/changelog.md"
directory = "changelog/"
title_format = "## Input4MIPs CVs {version} ({project_date})"
underlines = [
    "",
    "",
    "",
]
issue_format = "[#{issue}](https://github.com/PCMDI/Input4MIPs_CVs/pull/{issue})"
type = [
    { directory = "breaking", name = "âš ï¸ Breaking Changes", showcontent = true },
    { directory = "deprecation", name = "ğŸ—‘ï¸ Deprecations", showcontent = true },
    { directory = "feature", name = "ğŸ†• Features", showcontent = true },
    { directory = "improvement", name = "ğŸ‰ Improvements", showcontent = true },
    { directory = "fix", name = "ğŸ› Bug Fixes", showcontent = true },
    { directory = "docs", name = "ğŸ“š Improved Documentation", showcontent = true },
    { directory = "trivial", name = "ğŸ”§ Trivial/Internal Changes", showcontent = false },
]

